name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Или ваша основная ветка

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Inject Yandex Geo
        run: sed -i 's|<!-- YANDEX_GEO -->|<script>window.VITE_YANDEX_GEO_API_KEY="${{ secrets.VITE_YANDEX_GEO_API_KEY }}"</script>|' dist/index.html

      - name: Inject Yandex Map
        run: sed -i 's|<!-- YANDEX_YMAP -->|<script>window.VITE_YANDEX_YMAP_API_KEY="${{ secrets.VITE_YANDEX_YMAP_API_KEY }}"</script>|' dist/index.html

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          VITE_YANDEX_GEO_API_KEY: ${{ secrets.VITE_YANDEX_GEO_API_KEY }}
          VITE_YANDEX_YMAP_API_KEY: ${{ secrets.VITE_YANDEX_YMAP_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
